### PR TITLE
Adding file1.txt 

### PR DESCRIPTION
**Pull request by zara-iot-developer1**
Hi Manager,

Please review and approve.

Regards

developer1

### CODE REVIEW

**Comment by zara-iot** [comment]
Hi developer1,
Please add another file and send it back to me.

Regards
Manager

**Comment by zara-iot-developer1** [comment]
Hi Manager,
I have added file1.txt as you requested. Please review and approve.

Regards
developer1

**Comment by zara-iot** [comment]
Hi developer1,
good job. Please go ahead and merge with the base code.

Regards

Manager

**Comment by zara-iot-developer1** [comment]
Hi,
Ok, I am going to merge branch1 with the base code and close the pull request.

Regards
developer1

**Comment by zara-iot** [comment]
Hi developer1,

I think you forgot to merge the changes from branch1 to the master branch. Please merge the changes.

regards

Manager

**Comment by zara-iot-developer1** [comment]
Hi Manager,
Could  you do it please. I do not have access for merging.

Regards

developer1

**Comment by zara-iot** [comment]
Hi,
I will do.

Regards

**Pull request merged**
